server:
  port: 9092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_srv_dep
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
        format_sql: true
    show-sql: true